"""added profileurl in user and update is read to status in messages

Revision ID: 5548ced79565
Revises: ae4e84600039
Create Date: 2025-07-10 06:05:26.632572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5548ced79565'
down_revision: Union[str, Sequence[str], None] = 'ae4e84600039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
        # 1. Create enum type first
    messagestatus = sa.Enum('sent', 'delivered', 'read', name='messagestatus')
    messagestatus.create(op.get_bind(), checkfirst=True)
    
    op.add_column('messages', sa.Column('status', sa.Enum('sent', 'delivered', 'read', name='messagestatus'), nullable=True))
    op.drop_column('messages', 'is_read')
    op.add_column('users', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'file_type')
    op.drop_column('users', 'file_url')
    op.add_column('messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
