"""Add password to chatroom

Revision ID: 5c7cb168606c
Revises: e91b185dea20
Create Date: 2025-07-02 08:34:35.217638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7cb168606c'
down_revision: Union[str, Sequence[str], None] = 'e91b185dea20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('chatroom', sa.Column('password', sa.String(), nullable=True))
    # op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    # op.add_column('messages', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_type')
    op.drop_column('messages', 'file_url')
    op.drop_column('chatroom', 'password')
    # ### end Alembic commands ###
