"""Clean schema

Revision ID: a2c9c11ef6ae
Revises: 5c7cb168606c
Create Date: 2025-07-02 17:13:04.407411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c9c11ef6ae'
down_revision: Union[str, Sequence[str], None] = '5c7cb168606c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatroom', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatroom', 'password')
    # ### end Alembic commands ###
