"""update tables foe user to user communication

Revision ID: ae4e84600039
Revises: a2c9c11ef6ae
Create Date: 2025-07-07 18:46:30.908905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4e84600039'
down_revision: Union[str, Sequence[str], None] = 'a2c9c11ef6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatroom', 'is_deleted')
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_column('messages', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('messages', 'is_read')
    op.drop_column('messages', 'receiver_id')
    op.add_column('chatroom', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
