"""add profile_image to User

Revision ID: b0459cbd8ae5
Revises: 5c7cb168606c
Create Date: 2025-07-13 18:34:36.269037

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0459cbd8ae5"
down_revision: str | Sequence[str] | None = "5c7cb168606c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profile_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image")
    # ### end Alembic commands ###
